import { theme } from './color'
import { tokenColors } from './token'

export default function getTheme() {
  return {
    name: 'E-Ink',
    base: 'hc-light',
    $schema: 'vscode://schemas/color-theme',
    colors: {
      // Contrast colors
      contrastActiveBorder: theme.border,
      contrastBorder: theme.border,

      // Base colors
      focusBorder: theme.border,
      foreground: theme.foreground,
      'widget.border': theme.border,
      'widget.shadow': theme.shadow,
      'selection.background': theme.background2,
      descriptionForeground: theme.foreground,
      // errorForeground: themes.error,
      'icon.foreground': theme.foreground,
      'sash.hoverBorder': theme.border,

      // Window border
      'window.activeBorder': theme.border,
      'window.inactiveBorder': theme.border,

      // Text colors
      'textBlockQuote.background': theme.background,
      'textBlockQuote.border': theme.border,
      'textCodeBlock.background': theme.background,
      'textLink.foreground': theme.foreground2,
      'textLink.activeForeground': theme.foreground,
      'textPreformat.foreground': theme.background,
      'textPreformat.background': theme.background2,
      'textSeparator.foreground': theme.foreground,

      // Action colors
      'toolbar.hoverBackground': theme.background,
      'toolbar.hoverOutline': theme.outline,
      'toolbar.activeBackground': theme.background3,

      // Button control
      'button.background': theme.background,
      'button.foreground': theme.foreground,
      'button.border': theme.border,
      'button.separator': theme.separator,
      'button.hoverBackground': theme.background2,
      // 'button.secondaryForeground': themes.primary,
      // 'button.secondaryBackground': themes.background,
      // 'button.secondaryHoverBackground': themes.primary,
      'checkbox.background': theme.background,
      'checkbox.foreground': theme.foreground,
      'checkbox.border': theme.border,
      'checkbox.selectBackground': theme.background3,
      'checkbox.selectBorder': theme.border,

      // Dropdown control
      'dropdown.background': theme.background,
      'dropdown.border': theme.border,
      'dropdown.foreground': theme.foreground,
      'dropdown.listBackground': theme.background,

      // Input control
      'input.background': theme.background,
      'input.border': theme.border,
      'input.foreground': theme.foreground,
      'input.placeholderForeground': theme.foreground2,
      'inputOption.activeBackground': theme.background,
      'inputOption.activeBorder': theme.border,
      'inputOption.activeForeground': theme.foreground,
      'inputOption.hoverBackground': theme.background,
      // 'inputValidation.errorBackground': themes.background,
      // 'inputValidation.errorForeground': themes.warn,
      // 'inputValidation.errorBorder': themes.border,
      // 'inputValidation.infoBackground': themes.background,
      // 'inputValidation.infoForeground': themes.foreground,
      // 'inputValidation.infoBorder': themes.border,
      // 'inputValidation.warningBackground': themes.background,
      // 'inputValidation.warningForeground': themes.foreground,
      // 'inputValidation.warningBorder': themes.border,

      // Scrollbar control
      'scrollbar.shadow': theme.shadow,
      'scrollbarSlider.activeBackground': theme.background4,
      'scrollbarSlider.background': theme.background2,
      'scrollbarSlider.hoverBackground': theme.background4,

      // Badge
      'badge.foreground': theme.foreground,
      'badge.background': theme.background,

      // Progress bar
      'progressBar.background': theme.background3,

      // Lists and trees
      'list.activeSelectionBackground': theme.background,
      'list.activeSelectionForeground': theme.foreground,
      'list.activeSelectionIconForeground': theme.foreground,
      'list.dropBackground': theme.background2,
      'list.focusBackground': theme.background,
      'list.focusForeground': theme.foreground,
      'list.focusHighlightForeground': theme.foreground,
      'list.focusOutline': theme.outline,
      'list.focusAndSelectionOutline': theme.outline,
      'list.highlightForeground': theme.foreground,
      'list.hoverBackground': theme.background2,
      'list.hoverForeground': theme.foreground,
      'list.inactiveSelectionBackground': theme.background,
      'list.inactiveSelectionForeground': theme.foreground,
      'list.inactiveSelectionIconForeground': theme.foreground,
      'list.inactiveFocusBackground': theme.background,
      'list.inactiveFocusOutline': theme.outline,
      'list.invalidItemForeground': theme.foreground,
      // 'list.errorForeground': themes.error,
      // 'list.warningForeground': themes.warn,
      'listFilterWidget.background': theme.background,
      'listFilterWidget.outline': theme.outline,
      'listFilterWidget.noMatchesOutline': theme.outline,
      'listFilterWidget.shadow': theme.shadow,
      'list.filterMatchBackground': theme.background2,
      'list.filterMatchBorder': theme.border,
      'list.deemphasizedForeground': theme.foreground,
      'tree.indentGuidesStroke': theme.stroke,
      'tree.inactiveIndentGuidesStroke': theme.stroke,
      'tree.tableColumnsBorder': theme.border,
      'tree.tableOddRowsBackground': theme.background,

      // Activity Bar
      'activityBar.background': theme.background,
      'activityBar.dropBorder': theme.border,
      'activityBar.foreground': theme.foreground,
      'activityBar.inactiveForeground': theme.foreground,
      'activityBar.border': theme.border,
      'activityBarBadge.background': theme.background,
      'activityBarBadge.foreground': theme.foreground,
      'activityBar.activeBorder': theme.border,
      'activityBar.activeBackground': theme.background,
      'activityBar.activeFocusBorder': theme.border,

      // Profiles
      'profileBadge.background': theme.background,
      'profileBadge.foreground': theme.foreground,

      // Side Bar
      'sideBar.background': theme.background,
      'sideBar.foreground': theme.foreground,
      'sideBar.border': theme.border,
      'sideBar.dropBackground': theme.background2,
      'sideBarTitle.foreground': theme.foreground,
      'sideBarSectionHeader.background': theme.background,
      'sideBarSectionHeader.foreground': theme.foreground,
      'sideBarSectionHeader.border': theme.border,

      // Minimap
      // 'minimap.findMatchHighlight': '',
      // 'minimap.selectionHighlight': '',
      // 'minimap.errorHighlight': '',
      // 'minimap.warningHighlight': '',
      // 'minimap.background': '',
      // 'minimap.selectionOccurrenceHighlight': '',
      // 'minimap.foregroundOpacity': '',
      // 'minimap.infoHighlight': '',
      // 'minimapSlider.background': '',
      // 'minimapSlider.hoverBackground': '',
      // 'minimapSlider.activeBackground': '',
      // 'minimapGutter.addedBackground': '',
      // 'minimapGutter.modifiedBackground': '',
      // 'minimapGutter.deletedBackground': '',

      // Editor Groups & Tabs
      'editorGroup.border': theme.border,
      'editorGroup.dropBackground': theme.background2,
      'editorGroupHeader.noTabsBackground': theme.background,
      'editorGroupHeader.tabsBackground': theme.background,
      'editorGroupHeader.tabsBorder': theme.border,
      'editorGroupHeader.border': theme.border,
      'editorGroup.emptyBackground': theme.background,
      'editorGroup.focusedEmptyBorder': theme.border,
      'editorGroup.dropIntoPromptForeground': theme.foreground,
      'editorGroup.dropIntoPromptBackground': theme.background,
      'editorGroup.dropIntoPromptBorder': theme.border,
      'tab.activeBackground': theme.background,
      'tab.unfocusedActiveBackground': theme.background,
      'tab.activeForeground': theme.foreground,
      'tab.border': theme.border,
      'tab.activeBorder': theme.border,
      'tab.unfocusedActiveBorder': theme.border,
      'tab.activeBorderTop': theme.border,
      'tab.unfocusedActiveBorderTop': theme.border,
      'tab.lastPinnedBorder': theme.border,
      'tab.inactiveBackground': theme.background,
      'tab.unfocusedInactiveBackground': theme.background,
      'tab.inactiveForeground': theme.foreground,
      'tab.unfocusedActiveForeground': theme.foreground,
      'tab.unfocusedInactiveForeground': theme.foreground,
      'tab.hoverBackground': theme.background,
      'tab.unfocusedHoverBackground': theme.background,
      'tab.hoverForeground': theme.foreground,
      'tab.unfocusedHoverForeground': theme.foreground,
      'tab.hoverBorder': theme.border,
      'tab.unfocusedHoverBorder': theme.border,
      'tab.activeModifiedBorder': theme.border,
      'tab.inactiveModifiedBorder': theme.border,
      'tab.unfocusedActiveModifiedBorder': theme.border,
      'tab.unfocusedInactiveModifiedBorder': theme.border,
      'editorPane.background': theme.background,
      'sideBySideEditor.horizontalBorder': theme.border,
      'sideBySideEditor.verticalBorder': theme.border,

      // Editor colors
      'editor.background': theme.background,
      'editor.foreground': theme.foreground,
      'editorLineNumber.foreground': theme.foreground,
      'editorLineNumber.activeForeground': theme.foreground2,
      'editorLineNumber.dimmedForeground': theme.foreground,
      'editorCursor.background': theme.background,
      'editorCursor.foreground': theme.foreground,
      'editor.selectionBackground': theme.background2,
      'editor.selectionForeground': theme.foreground3,
      'editor.inactiveSelectionBackground': theme.background2,
      // 'editor.selectionHighlightBackground': themes.background,
      // 'editor.selectionHighlightBorder': themes.border,
      // 'editor.wordHighlightBackground': themes.background,
      // 'editor.wordHighlightBorder': themes.border,
      // 'editor.wordHighlightStrongBackground': themes.background,
      // 'editor.wordHighlightStrongBorder': themes.border,
      // 'editor.wordHighlightTextBackground': themes.background,
      // 'editor.wordHighlightTextBorder': themes.border,
      'editor.findMatchBackground': theme.background2,
      // 'editor.findMatchHighlightBackground': themes.background,
      'editor.findRangeHighlightBackground': theme.background,
      'editor.findMatchBorder': theme.border,
      // 'editor.findMatchHighlightBorder': colors.white,
      'editor.findRangeHighlightBorder': theme.border,
      'search.resultsInfoForeground': theme.foreground,
      // 'searchEditor.findMatchBackground':themes.foreground,
      // 'searchEditor.findMatchBorder':themes.foreground,
      // 'searchEditor.textInputBorder':themes.foreground,
      // 'editor.hoverHighlightBackground':themes.background,
      // 'editor.lineHighlightBackground':themes.primary,
      'editor.lineHighlightBorder': theme.border,
      // 'editorUnicodeHighlight.border':themes.primary,
      // 'editorUnicodeHighlight.background':themes.primary,
      'editorLink.activeForeground': theme.foreground2,
      // 'editor.rangeHighlightBackground':themes.primary,
      // 'editor.rangeHighlightBorder':themes.primary,
      'editor.symbolHighlightBackground': theme.background2,
      'editor.symbolHighlightBorder': theme.border,
      'editorWhitespace.foreground': theme.foreground3,
      // 'editorIndentGuide.background': colors.lightpink,
      // 'editorIndentGuide.background1': themes.primary,
      // 'editorIndentGuide.background2': themes.secondary,
      // 'editorIndentGuide.background3': colors.green,
      // 'editorIndentGuide.background4': colors.red,
      // 'editorIndentGuide.background5': colors.orange,
      // 'editorIndentGuide.background6': colors.blue,
      // 'editorIndentGuide.activeBackground': colors.lightpink,
      // 'editorIndentGuide.activeBackground1': themes.primary,
      // 'editorIndentGuide.activeBackground2': themes.secondary,
      // 'editorIndentGuide.activeBackground3': colors.green,
      // 'editorIndentGuide.activeBackground4': colors.red,
      // 'editorIndentGuide.activeBackground5': colors.orange,
      // 'editorIndentGuide.activeBackground6': colors.blue,
      // 'editorInlayHint.background': themes.background,
      // 'editorInlayHint.foreground': themes.foreground,
      // 'editorInlayHint.typeForeground': themes.primary,
      // 'editorInlayHint.typeBackground': themes.primary,
      // 'editorInlayHint.parameterForeground': themes.primary,
      // 'editorInlayHint.parameterBackground': themes.primary,
      'editorRuler.foreground': theme.foreground,
      'editor.linkedEditingBackground': theme.background3,
      'editorCodeLens.foreground': theme.foreground,
      'editorLightBulb.foreground': theme.foreground,
      'editorLightBulbAutoFix.foreground': theme.foreground,
      // 'editorBracketMatch.background':themes.primary,
      // 'editorBracketMatch.border':themes.primary,
      // 'editorBracketHighlight.foreground1': themes.primary,
      // 'editorBracketHighlight.foreground2': themes.primary,
      // 'editorBracketHighlight.foreground3': themes.primary,
      // 'editorBracketHighlight.foreground4': themes.primary,
      // 'editorBracketHighlight.foreground5': themes.primary,
      // 'editorBracketHighlight.foreground6': themes.primary,
      // 'editorBracketHighlight.unexpectedBracket.foreground': themes.secondary,
      // 'editorBracketPairGuide.activeBackground1':themes.primary,
      // 'editorBracketPairGuide.activeBackground2':themes.primary,
      // 'editorBracketPairGuide.activeBackground3':themes.primary,
      // 'editorBracketPairGuide.activeBackground4':themes.primary,
      // 'editorBracketPairGuide.activeBackground5':themes.primary,
      // 'editorBracketPairGuide.activeBackground6':themes.primary,
      // 'editorBracketPairGuide.background1':themes.primary,
      // 'editorBracketPairGuide.background2':themes.primary,
      // 'editorBracketPairGuide.background3':themes.primary,
      // 'editorBracketPairGuide.background4':themes.primary,
      // 'editorBracketPairGuide.background5':themes.primary,
      // 'editorBracketPairGuide.background6':themes.primary,
      // 'editor.foldBackground':themes.primary,
      'editorOverviewRuler.background': theme.background,
      'editorOverviewRuler.border': theme.border,
      'editorOverviewRuler.findMatchForeground': theme.foreground,
      // 'editorOverviewRuler.rangeHighlightForeground':themes.primary,
      // 'editorOverviewRuler.selectionHighlightForeground':themes.primary,
      // 'editorOverviewRuler.wordHighlightForeground':themes.primary,
      // 'editorOverviewRuler.wordHighlightStrongForeground':themes.primary,
      // 'editorOverviewRuler.wordHighlightTextForeground':themes.primary,
      // 'editorOverviewRuler.modifiedForeground':themes.primary,
      // 'editorOverviewRuler.addedForeground':themes.primary,
      // 'editorOverviewRuler.deletedForeground':themes.primary,
      // 'editorOverviewRuler.errorForeground':themes.primary,
      // 'editorOverviewRuler.warningForeground':themes.primary,
      // 'editorOverviewRuler.infoForeground':themes.primary,
      // 'editorOverviewRuler.bracketMatchForeground':themes.primary,
      // 'editorError.foreground':themes.error,
      // 'editorError.border':themes.error,
      // 'editorError.background':colors.white,
      // 'editorWarning.foreground':themes.primary,
      // 'editorWarning.border':themes.primary,
      // 'editorWarning.background':themes.primary,
      // 'editorInfo.foreground':themes.primary,
      // 'editorInfo.border':themes.primary,
      // 'editorInfo.background':themes.primary,
      // 'editorHint.foreground':themes.primary,
      // 'editorHint.border':themes.border,
      // 'problemsErrorIcon.foreground':themes.secondary,
      // 'problemsWarningIcon.foreground':themes.primary,
      // 'problemsInfoIcon.foreground':themes.primary,
      // 'editorUnnecessaryCode.border': themes.primary,
      // 'editorUnnecessaryCode.opacity': themes.primary,
      'editorGutter.background': theme.background,
      'editorGutter.modifiedBackground': theme.background3,
      // 'editorGutter.addedBackground':themes.primary,
      // 'editorGutter.deletedBackground':themes.primary,
      // 'editorGutter.commentRangeForeground':themes.secondary,
      // 'editorGutter.commentGlyphForeground':themes.primary,
      // 'editorGutter.commentUnresolvedGlyphForeground':themes.primary,
      // 'editorGutter.foldingControlForeground':themes.primary,
      // 'editorCommentsWidget.resolvedBorder':themes.primary,
      // 'editorCommentsWidget.unresolvedBorder':themes.primary,
      // 'editorCommentsWidget.rangeBackground':themes.primary,
      // 'editorCommentsWidget.rangeActiveBackground':themes.primary,

      // Diff editor colors
      // 'diffEditor.insertedTextBackground':themes.primaryBackground,
      'diffEditor.insertedTextBorder': theme.border,
      // 'diffEditor.removedTextBackground':themes.primaryBackground,
      'diffEditor.removedTextBorder': theme.border,
      'diffEditor.border': theme.border,
      // 'diffEditor.diagonalFill': themes.secondary,
      // 'diffEditor.insertedLineBackground':themes.primary,
      // 'diffEditor.removedLineBackground':themes.primary,
      // 'diffEditorGutter.insertedLineBackground':themes.primary,
      // 'diffEditorGutter.removedLineBackground':themes.primary,
      // 'diffEditorOverview.insertedForeground':themes.primary,
      // 'diffEditorOverview.removedForeground':themes.primary,
      'diffEditor.unchangedRegionBackground': theme.background,
      'diffEditor.unchangedRegionForeground': theme.foreground2,
      'diffEditor.unchangedCodeBackground': theme.background,
      // 'diffEditor.move.border':themes.secondary,
      // 'diffEditor.moveActive.border':themes.primary,

      // Chat colors
      // 'chat.requestBorder': themes.primary,
      // 'chat.slashCommandBackground': themes.primary,
      // 'chat.slashCommandForeground': themes.primary,

      // Inline Chat colors
      // 'inlineChat.background':themes.primary,
      // 'inlineChat.border':themes.primary,
      // 'inlineChat.shadow':themes.primary,
      // 'inlineChat.regionHighlight':themes.primary,
      // 'inlineChatInput.border':themes.primary,
      // 'inlineChatInput.focusBorder':themes.primary,
      // 'inlineChatInput.placeholderForeground':themes.primary,
      // 'inlineChatInput.background':themes.primary,
      // 'inlineChatDiff.inserted':themes.primary,
      // 'inlineChatDiff.removed':themes.primary,

      // Editor widget colors
      // 'editorWidget.foreground': themes.foreground,
      // 'editorWidget.background': themes.background,
      // 'editorWidget.border': themes.border,
      // 'editorWidget.resizeBorder': themes.border,
      // 'editorSuggestWidget.background': themes.primary,
      // 'editorSuggestWidget.border': themes.primary,
      // 'editorSuggestWidget.foreground': themes.primary,
      // 'editorSuggestWidget.focusHighlightForeground': themes.primary,
      // 'editorSuggestWidget.highlightForeground': themes.primary,
      // 'editorSuggestWidget.selectedBackground': themes.primary,
      // 'editorSuggestWidget.selectedForeground': themes.primary,
      // 'editorSuggestWidget.selectedIconForeground': themes.primary,
      // 'editorSuggestWidgetStatus.foreground': themes.primary,
      // 'editorHoverWidget.foreground': themes.foreground,
      // 'editorHoverWidget.background': themes.background,
      // 'editorHoverWidget.border': themes.border,
      // 'editorHoverWidget.highlightForeground': themes.primary,
      // 'editorHoverWidget.statusBarBackground': themes.primary,
      // 'editorGhostText.border': themes.primary,
      // 'editorGhostText.background': themes.primary,
      // 'editorGhostText.foreground': themes.primary,
      // 'editorStickyScroll.background': themes.primary,
      // 'editorStickyScrollHover.background': themes.primary,
      // 'debugExceptionWidget.background': themes.primary,
      // 'debugExceptionWidget.border': themes.primary,
      // 'editorMarkerNavigation.background':themes.primary,
      // 'editorMarkerNavigationError.background':themes.primary,
      // 'editorMarkerNavigationWarning.background':themes.primary,
      // 'editorMarkerNavigationInfo.background':themes.primary,
      // 'editorMarkerNavigationError.headerBackground':themes.primary,
      // 'editorMarkerNavigationWarning.headerBackground':themes.primary,
      // 'editorMarkerNavigationInfo.headerBackground':themes.primary,

      // Peek view colors
      // 'peekView.border': themes.primary,
      // 'peekViewEditor.background': themes.primary,
      // 'peekViewEditorGutter.background': themes.primary,
      // 'peekViewEditor.matchHighlightBackground': themes.primary,
      // 'peekViewEditor.matchHighlightBorder': themes.primary,
      // 'peekViewResult.background': themes.primary,
      // 'peekViewResult.fileForeground': themes.primary,
      // 'peekViewResult.lineForeground': themes.primary,
      // 'peekViewResult.matchHighlightBackground': themes.primary,
      // 'peekViewResult.selectionBackground': themes.primary,
      // 'peekViewResult.selectionForeground': themes.primary,
      // 'peekViewTitle.background': themes.primary,
      // 'peekViewTitleDescription.foreground': themes.primary,
      // 'peekViewTitleLabel.foreground': themes.primary,
      // 'peekViewEditorStickyScroll.background': themes.primary,

      // Merge conflicts colors
      // 'merge.currentHeaderBackground': themes.primary,
      // 'merge.currentContentBackground': themes.primary,
      // 'merge.incomingHeaderBackground': themes.primary,
      // 'merge.incomingContentBackground': themes.primary,
      // 'merge.border': themes.primary,
      // 'merge.commonContentBackground': themes.primary,
      // 'merge.commonHeaderBackground': themes.primary,
      // 'editorOverviewRuler.currentContentForeground': themes.primary,
      // 'editorOverviewRuler.incomingContentForeground': themes.primary,
      // 'editorOverviewRuler.commonContentForeground': themes.primary,
      // 'editorOverviewRuler.commentForeground': themes.primary,
      // 'editorOverviewRuler.commentUnresolvedForeground': themes.primary,
      // 'mergeEditor.change.background': themes.primary,
      // 'mergeEditor.change.word.background': themes.primary,
      // 'mergeEditor.conflict.unhandledUnfocused.border': themes.primary,
      // 'mergeEditor.conflict.unhandledFocused.border': themes.primary,
      // 'mergeEditor.conflict.handledUnfocused.border': themes.primary,
      // 'mergeEditor.conflict.handledFocused.border': themes.primary,
      // 'mergeEditor.conflict.handled.minimapOverViewRuler': themes.primary,
      // 'mergeEditor.conflict.unhandled.minimapOverViewRuler': themes.primary,
      // 'mergeEditor.conflictingLines.background': themes.primary,
      // 'mergeEditor.changeBase.background': themes.primary,
      // 'mergeEditor.changeBase.word.background': themes.primary,
      // 'mergeEditor.conflict.input1.background': themes.primary,
      // 'mergeEditor.conflict.input2.background': themes.primary,

      // Panel colors
      'panel.background': theme.background,
      'panel.border': theme.border,
      'panel.dropBorder': theme.border2,
      'panelTitle.activeBorder': theme.border,
      'panelTitle.activeForeground': theme.foreground,
      'panelTitle.inactiveForeground': theme.foreground,
      'panelInput.border': theme.border,
      // 'panelSection.border': themes.error,
      // 'panelSection.dropBackground': themes.background,
      // 'panelSectionHeader.background': themes.primary,
      // 'panelSectionHeader.foreground': themes.primary,
      // 'panelSectionHeader.border': themes.primary,

      // Status Bar colors
      'statusBar.background': theme.background,
      'statusBar.foreground': theme.foreground,
      'statusBar.border': theme.border,
      'statusBar.debuggingBackground': theme.background,
      'statusBar.debuggingForeground': theme.foreground,
      'statusBar.debuggingBorder': theme.border,
      'statusBar.noFolderForeground': theme.foreground,
      'statusBar.noFolderBackground': theme.background,
      'statusBar.noFolderBorder': theme.border,
      // 'statusBarItem.activeBackground': themes.primary,
      // 'statusBarItem.hoverForeground': themes.foreground,
      // 'statusBarItem.hoverBackground': themes.primary,
      // 'statusBarItem.prominentForeground': themes.error,
      // 'statusBarItem.prominentBackground': themes.primary,
      // 'statusBarItem.prominentHoverForeground': themes.primary,
      // 'statusBarItem.prominentHoverBackground': themes.primary,
      // 'statusBarItem.remoteBackground': themes.primary,
      // 'statusBarItem.remoteForeground': themes.primary,
      // 'statusBarItem.remoteHoverBackground': themes.primary,
      // 'statusBarItem.remoteHoverForeground': themes.primary,
      // 'statusBarItem.errorBackground': themes.primary,
      // 'statusBarItem.errorForeground': themes.error,
      // 'statusBarItem.errorHoverBackground': themes.primary,
      // 'statusBarItem.errorHoverForeground': themes.primary,
      // 'statusBarItem.warningBackground': themes.primary,
      // 'statusBarItem.warningForeground': themes.primary,
      // 'statusBarItem.warningHoverBackground': themes.primary,
      // 'statusBarItem.warningHoverForeground': themes.primary,
      // 'statusBarItem.compactHoverBackground': themes.primary,
      // 'statusBarItem.focusBorder': themes.primary,
      // 'statusBar.focusBorder': themes.primary,
      // 'statusBarItem.offlineBackground': themes.primary,
      // 'statusBarItem.offlineForeground': themes.primary,
      // 'statusBarItem.offlineHoverForeground': themes.primary,
      // 'statusBarItem.offlineHoverBackground': themes.primary,

      // Title Bar colors
      // 'titleBar.activeBackground': themes.background,
      // 'titleBar.activeForeground': themes.primary,
      // 'titleBar.inactiveBackground': themes.background,
      // 'titleBar.inactiveForeground': themes.primary,
      // 'titleBar.border': themes.primary,

      // Menu Bar colors
      // 'menubar.selectionForeground': themes.primary,
      // 'menubar.selectionBackground': themes.primary,
      // 'menubar.selectionBorder': themes.primary,
      // 'menu.foreground': themes.primary,
      // 'menu.background': themes.primary,
      // 'menu.selectionForeground': themes.primary,
      // 'menu.selectionBackground': themes.primary,
      // 'menu.selectionBorder': themes.primary,
      // 'menu.separatorBackground': themes.primary,
      // 'menu.border': themes.primary,

      // Command Center colors
      // 'commandCenter.foreground': themes.primary,
      // 'commandCenter.activeForeground': themes.primary,
      // 'commandCenter.background': themes.primary,
      // 'commandCenter.activeBackground': themes.primary,
      // 'commandCenter.border': themes.primary,
      // 'commandCenter.inactiveForeground': themes.primary,
      // 'commandCenter.inactiveBorder': themes.primary,
      // 'commandCenter.activeBorder': themes.primary,
      // 'commandCenter.debuggingBackground': themes.primary,

      // Notification colors
      'notificationCenter.border': theme.border,
      'notificationCenterHeader.foreground': theme.foreground,
      'notificationCenterHeader.background': theme.background,
      'notificationToast.border': theme.border,
      'notifications.foreground': theme.foreground,
      'notifications.background': theme.background,
      'notifications.border': theme.border,
      // 'notificationLink.foreground': themes.primary,
      // 'notificationsErrorIcon.foreground': themes.primary,
      // 'notificationsWarningIcon.foreground': themes.primary,
      // 'notificationsInfoIcon.foreground': themes.primary,

      // Banner colors
      // 'banner.background': themes.primary,
      // 'banner.foreground': themes.primary,
      // 'banner.iconForeground': themes.primary,

      // Extensions colors
      'extensionButton.prominentForeground': theme.foreground,
      // 'extensionButton.prominentBackground': themes.background,
      'extensionButton.prominentHoverBackground': theme.background,
      // 'extensionButton.background': themes.primary,
      'extensionButton.foreground': theme.foreground,
      'extensionButton.hoverBackground': theme.background,
      // 'extensionButton.separator': themes.primary,
      // 'extensionBadge.remoteBackground': themes.primary,
      // 'extensionBadge.remoteForeground': themes.primary,
      // 'extensionIcon.starForeground': themes.primary,
      // 'extensionIcon.verifiedForeground': themes.primary,
      // 'extensionIcon.preReleaseForeground': themes.primary,
      // 'extensionIcon.sponsorForeground': themes.primary,

      // Quick picker colors
      // 'pickerGroup.border': themes.primary,
      // 'pickerGroup.foreground': themes.primary,
      // 'quickInput.background': themes.primary,
      // 'quickInput.foreground': themes.primary,
      // 'quickInputList.focusBackground': themes.primary,
      // 'quickInputList.focusForeground': themes.primary,
      // 'quickInputList.focusIconForeground': themes.primary,
      // 'quickInputTitle.background': themes.primary,

      // Keybinding label colors
      'keybindingLabel.background': theme.background,
      'keybindingLabel.foreground': theme.foreground,
      'keybindingLabel.border': theme.border,
      'keybindingLabel.bottomBorder': theme.border,

      // Keyboard shortcut table colors
      'keybindingTable.headerBackground': theme.background,
      'keybindingTable.rowsBackground': theme.background,

      // Integrated Terminal colors
      'terminal.background': theme.background,
      'terminal.border': theme.border,
      'terminal.foreground': theme.foreground,
      // 'terminal.ansiBlack': themes.primary,
      // 'terminal.ansiBlue': themes.primary,
      // 'terminal.ansiBrightBlack': themes.primary,
      // 'terminal.ansiBrightBlue': themes.primary,
      // 'terminal.ansiBrightCyan': themes.primary,
      // 'terminal.ansiBrightGreen': themes.primary,
      // 'terminal.ansiBrightMagenta': themes.primary,
      // 'terminal.ansiBrightRed': themes.primary,
      // 'terminal.ansiBrightWhite': themes.primary,
      // 'terminal.ansiBrightYellow': themes.primary,
      // 'terminal.ansiCyan': themes.primary,
      // 'terminal.ansiGreen': themes.primary,
      // 'terminal.ansiMagenta': themes.primary,
      // 'terminal.ansiRed': themes.primary,
      // 'terminal.ansiWhite': themes.primary,
      // 'terminal.ansiYellow': themes.primary,
      // 'terminal.selectionBackground': themes.primary,
      // 'terminal.selectionForeground': themes.primary,
      // 'terminal.inactiveSelectionBackground': themes.primary,
      'terminal.findMatchBackground': theme.background,
      'terminal.findMatchBorder': theme.border,
      // 'terminal.findMatchHighlightBackground': themes.primary,
      'terminal.findMatchHighlightBorder': theme.border,
      // 'terminal.hoverHighlightBackground': themes.primary,
      'terminalCursor.background': theme.background,
      'terminalCursor.foreground': theme.foreground,
      // 'terminal.dropBackground': themes.primary,
      // 'terminal.tab.activeBorder': themes.primary,
      // 'terminalCommandDecoration.defaultBackground': themes.primary,
      // 'terminalCommandDecoration.successBackground': themes.primary,
      // 'terminalCommandDecoration.errorBackground': themes.primary,
      // 'terminalOverviewRuler.cursorForeground': themes.primary,
      // 'terminalOverviewRuler.findMatchForeground': themes.primary,

      // Debug colors
      'debugToolBar.background': theme.background,
      'debugToolBar.border': theme.border,
      'editor.stackFrameHighlightBackground': theme.background2,
      'editor.focusedStackFrameHighlightBackground': theme.background2,
      'editor.inlineValuesForeground': theme.foreground,
      'editor.inlineValuesBackground': theme.background2,
      // 'debugView.exceptionLabelForeground': themes.primary,
      // 'debugView.exceptionLabelBackground': themes.primary,
      'debugView.stateLabelForeground': theme.foreground,
      'debugView.stateLabelBackground': theme.background2,
      'debugView.valueChangedHighlight': theme.highlight,
      'debugTokenExpression.name': theme.highlight2,
      // 'debugTokenExpression.value': themes.primary,
      // 'debugTokenExpression.string': themes.primary,
      // 'debugTokenExpression.boolean': themes.primary,
      // 'debugTokenExpression.number': themes.primary,
      // 'debugTokenExpression.error': themes.primary,

      // Testing colors
      // 'testing.iconFailed': themes.primary,
      // 'testing.iconErrored': themes.primary,
      // 'testing.iconPassed': themes.primary,
      // 'testing.runAction': themes.primary,
      // 'testing.iconQueued': themes.primary,
      // 'testing.iconUnset': themes.primary,
      // 'testing.iconSkipped': themes.primary,
      // 'testing.peekBorder': themes.primary,
      // 'testing.peekHeaderBackground': themes.primary,
      // 'testing.message.error.decorationForeground': themes.primary,
      // 'testing.message.error.lineBackground': themes.primary,
      // 'testing.message.info.decorationForeground': themes.primary,
      // 'testing.message.info.lineBackground': themes.primary,

      // Welcome page colors
      // 'welcomePage.background': themes.primary,
      // 'welcomePage.progress.background': themes.primary,
      // 'welcomePage.progress.foreground': themes.primary,
      // 'welcomePage.tileBackground': themes.primary,
      // 'welcomePage.tileHoverBackground': themes.primary,
      // 'welcomePage.tileBorder': themes.primary,
      // 'walkThrough.embeddedEditorBackground': themes.primary,
      // 'walkthrough.stepTitle.foreground': themes.primary,

      // Git colors
      // 'gitDecoration.addedResourceForeground': themes.primary,
      // 'gitDecoration.modifiedResourceForeground': themes.primary,
      // 'gitDecoration.deletedResourceForeground': themes.primary,
      // 'gitDecoration.renamedResourceForeground': themes.primary,
      // 'gitDecoration.stageModifiedResourceForeground': themes.primary,
      // 'gitDecoration.stageDeletedResourceForeground': themes.primary,
      // 'gitDecoration.untrackedResourceForeground': themes.primary,
      // 'gitDecoration.ignoredResourceForeground': themes.primary,
      // 'gitDecoration.conflictingResourceForeground': themes.primary,
      // 'gitDecoration.submoduleResourceForeground': themes.primary,

      // Settings Editor colors
      // 'settings.headerForeground': themes.primary,
      // 'settings.modifiedItemIndicator': themes.primary,
      // 'settings.dropdownBackground': themes.primary,
      // 'settings.dropdownForeground': themes.primary,
      // 'settings.dropdownBorder': themes.primary,
      // 'settings.dropdownListBorder': themes.primary,
      // 'settings.checkboxBackground': themes.primary,
      // 'settings.checkboxForeground': themes.primary,
      // 'settings.checkboxBorder': themes.primary,
      // 'settings.rowHoverBackground': themes.primary,
      // 'settings.textInputBackground': themes.primary,
      // 'settings.textInputForeground': themes.primary,
      // 'settings.textInputBorder': themes.primary,
      // 'settings.numberInputBackground': themes.primary,
      // 'settings.numberInputForeground': themes.primary,
      // 'settings.numberInputBorder': themes.primary,
      // 'settings.focusedRowBackground': themes.primary,
      // 'settings.focusedRowBorder': themes.primary,
      // 'settings.headerBorder': themes.primary,
      // 'settings.sashBorder': themes.primary,
      // 'settings.settingsHeaderHoverForeground': themes.primary,

      // Breadcrumbs colors
      'breadcrumb.foreground': theme.foreground,
      // 'breadcrumb.background': themes.primary,
      'breadcrumb.focusForeground': theme.foreground,
      'breadcrumb.activeSelectionForeground': theme.foreground,
      // 'breadcrumbPicker.background': themes.primary,

      // Snippets colors
      // 'editor.snippetTabstopHighlightBackground': themes.primary,
      // 'editor.snippetTabstopHighlightBorder': themes.primary,
      // 'editor.snippetFinalTabstopHighlightBackground': themes.primary,
      // 'editor.snippetFinalTabstopHighlightBorder': themes.primary,

      // Symbol Icons colors
      // 'symbolIcon.arrayForeground': themes.primary,
      // 'symbolIcon.booleanForeground': themes.primary,
      // 'symbolIcon.classForeground': themes.primary,
      // 'symbolIcon.colorForeground': themes.primary,
      // 'symbolIcon.constantForeground': themes.primary,
      // 'symbolIcon.constructorForeground': themes.primary,
      // 'symbolIcon.enumeratorForeground': themes.primary,
      // 'symbolIcon.enumeratorMemberForeground': themes.primary,
      // 'symbolIcon.eventForeground': themes.primary,
      // 'symbolIcon.fieldForeground': themes.primary,
      // 'symbolIcon.fileForeground': themes.primary,
      // 'symbolIcon.folderForeground': themes.primary,
      // 'symbolIcon.functionForeground': themes.primary,
      // 'symbolIcon.interfaceForeground': themes.primary,
      // 'symbolIcon.keyForeground': themes.primary,
      // 'symbolIcon.keywordForeground': themes.primary,
      // 'symbolIcon.methodForeground': themes.primary,
      // 'symbolIcon.moduleForeground': themes.primary,
      // 'symbolIcon.namespaceForeground': themes.primary,
      // 'symbolIcon.nullForeground': themes.primary,
      // 'symbolIcon.numberForeground': themes.primary,
      // 'symbolIcon.objectForeground': themes.primary,
      // 'symbolIcon.operatorForeground': themes.primary,
      // 'symbolIcon.packageForeground': themes.primary,
      // 'symbolIcon.propertyForeground': themes.primary,
      // 'symbolIcon.referenceForeground': themes.primary,
      // 'symbolIcon.snippetForeground': themes.primary,
      // 'symbolIcon.stringForeground': themes.primary,
      // 'symbolIcon.structForeground': themes.primary,
      // 'symbolIcon.textForeground': themes.primary,
      // 'symbolIcon.typeParameterForeground': themes.primary,
      // 'symbolIcon.unitForeground': themes.primary,
      // 'symbolIcon.variableForeground': themes.primary,

      // Debug Icons colors
      // 'debugIcon.breakpointForeground': themes.primary,
      // 'debugIcon.breakpointDisabledForeground': themes.primary,
      // 'debugIcon.breakpointUnverifiedForeground': themes.primary,
      // 'debugIcon.breakpointCurrentStackframeForeground': themes.primary,
      // 'debugIcon.breakpointStackframeForeground': themes.primary,
      // 'debugIcon.startForeground': themes.primary,
      // 'debugIcon.pauseForeground': themes.primary,
      // 'debugIcon.stopForeground': themes.primary,
      // 'debugIcon.disconnectForeground': themes.primary,
      // 'debugIcon.restartForeground': themes.primary,
      // 'debugIcon.stepOverForeground': themes.primary,
      // 'debugIcon.stepIntoForeground': themes.primary,
      // 'debugIcon.stepOutForeground': themes.primary,
      // 'debugIcon.continueForeground': themes.primary,
      // 'debugIcon.stepBackForeground': themes.primary,
      // 'debugConsole.infoForeground': themes.primary,
      // 'debugConsole.warningForeground': themes.primary,
      // 'debugConsole.errorForeground': themes.primary,
      // 'debugConsole.sourceForeground': themes.primary,
      // 'debugConsoleInputIcon.foreground': themes.primary,

      // Notebook colors
      // 'notebook.editorBackground':themes.primary,
      // 'notebook.cellBorderColor':themes.primary,
      // 'notebook.cellHoverBackground':themes.primary,
      // 'notebook.cellInsertionIndicator':themes.primary,
      // 'notebook.cellStatusBarItemHoverBackground':themes.primary,
      // 'notebook.cellToolbarSeparator':themes.primary,
      // 'notebook.cellEditorBackground':themes.primary,
      // 'notebook.focusedCellBackground':themes.primary,
      // 'notebook.focusedCellBorder':themes.primary,
      // 'notebook.focusedEditorBorder':themes.primary,
      // 'notebook.inactiveFocusedCellBorder':themes.primary,
      // 'notebook.inactiveSelectedCellBorder':themes.primary,
      // 'notebook.outputContainerBackgroundColor':themes.primary,
      // 'notebook.outputContainerBorderColor':themes.primary,
      // 'notebook.selectedCellBackground':themes.primary,
      // 'notebook.selectedCellBorder':themes.primary,
      // 'notebook.symbolHighlightBackground':themes.primary,
      // 'notebookScrollbarSlider.activeBackground':themes.primary,
      // 'notebookScrollbarSlider.background':themes.primary,
      // 'notebookScrollbarSlider.hoverBackground':themes.primary,
      // 'notebookStatusErrorIcon.foreground':themes.primary,
      // 'notebookStatusRunningIcon.foreground':themes.primary,
      // 'notebookStatusSuccessIcon.foreground':themes.primary,
      // 'notebookEditorOverviewRuler.runningCellForeground':themes.primary,

      // Chart colors
      // 'charts.foreground': themes.primary,
      // 'charts.lines': themes.primary,
      // 'charts.red': themes.primary,
      // 'charts.blue': themes.primary,
      // 'charts.yellow': themes.primary,
      // 'charts.orange': themes.primary,
      // 'charts.green': themes.primary,
      // 'charts.purple': themes.primary,

      // Ports Colors
      // 'ports.iconRunningProcessForeground':themes.primary,

      // Comments View colors
      // 'commentsView.resolvedIcon': themes.primary,
      // 'commentsView.unresolvedIcon': themes.primary,

      // Action Bar colors
      'actionBar.toggledBackground': theme.background2

      // Simple Find Widget
      // 'simpleFindWidget.sashBorder':themes.primary,
    },
    tokenColors
  }
}
