import { theme } from './color'
import { getTokenColors, getsemanticTokenColors } from './token'

function getThemeColors(isColor = false) {
  const h = (colors: readonly [string, string]) => isColor ? colors[1] : colors[0]

  return {
    // https://code.visualstudio.com/api/references/theme-color

    // Contrast colors
    'contrastActiveBorder': h(theme.border),
    'contrastBorder': h(theme.border),

    // Base colors
    'focusBorder': h(theme.border),
    'foreground': h(theme.foreground),
    'disabledForeground': h(theme.error),
    'widget.border': h(theme.border),
    'widget.shadow': h(theme.shadow),
    'selection.background': h(theme.background2),
    'descriptionForeground': h(theme.foreground),
    'errorForeground': h(theme.error),
    'icon.foreground': h(theme.foreground),
    'sash.hoverBorder': h(theme.border),

    // Window border
    'window.activeBorder': h(theme.border),
    'window.inactiveBorder': h(theme.border),

    // Text colors
    'textBlockQuote.background': h(theme.background),
    'textBlockQuote.border': h(theme.border),
    'textCodeBlock.background': h(theme.background),
    'textLink.foreground': h([theme.foreground2[0], theme.foreground3[1]]),
    'textLink.activeForeground': h(theme.foreground),
    'textPreformat.foreground': h(theme.background),
    'textPreformat.background': h(theme.background2),
    'textSeparator.foreground': h(theme.foreground),

    // Action colors
    'toolbar.hoverBackground': h(theme.background),
    'toolbar.hoverOutline': h(theme.outline),
    'toolbar.activeBackground': h(theme.background3),

    // Button control
    'button.background': h(theme.background),
    'button.foreground': h(theme.foreground),
    'button.border': h(theme.border),
    'button.separator': h(theme.separator),
    'button.hoverBackground': h(theme.background2),
    // 'button.secondaryForeground':h(theme.background),
    // 'button.secondaryBackground':h(theme.background),
    // 'button.secondaryHoverBackground':h(theme.background),
    'checkbox.background': h(theme.background),
    'checkbox.foreground': h(theme.foreground),
    'checkbox.border': h(theme.border),
    'checkbox.selectBackground': h(theme.background3),
    'checkbox.selectBorder': h(theme.border),

    // Dropdown control
    'dropdown.background': h(theme.background),
    'dropdown.border': h(theme.border),
    'dropdown.foreground': h(theme.foreground),
    'dropdown.listBackground': h(theme.background),

    // Input control
    'input.background': h(theme.background),
    'input.border': h(theme.border),
    'input.foreground': h(theme.foreground),
    'input.placeholderForeground': h([theme.foreground2[0], theme.foreground[1]]),
    'inputOption.activeBackground': h(theme.background),
    'inputOption.activeBorder': h(theme.border),
    'inputOption.activeForeground': h(theme.foreground),
    'inputOption.hoverBackground': h(theme.background),
    // 'inputValidation.errorBackground':h(theme.background),
    // 'inputValidation.errorForeground':h(theme.warn),
    // 'inputValidation.errorBorder':h(theme.border),
    // 'inputValidation.infoBackground':h(theme.background),
    // 'inputValidation.infoForeground':h(theme.foreground),
    // 'inputValidation.infoBorder':h(theme.border),
    // 'inputValidation.warningBackground':h(theme.background),
    // 'inputValidation.warningForeground':h(theme.foreground),
    // 'inputValidation.warningBorder':h(theme.border),

    // Scrollbar control
    'scrollbar.shadow': h(theme.shadow),
    'scrollbarSlider.activeBackground': h([theme.background4[0], theme.background3[1]]),
    'scrollbarSlider.background': h([theme.background2[0], theme.background2[1]]),
    'scrollbarSlider.hoverBackground': h([theme.background4[0], theme.background3[1]]),

    // Badge
    'badge.foreground': h(theme.foreground),
    'badge.background': h(theme.background),

    // Progress bar
    'progressBar.background': h(theme.background3),

    // Lists and trees
    'list.activeSelectionBackground': h(theme.background),
    'list.activeSelectionForeground': h(theme.foreground),
    'list.activeSelectionIconForeground': h(theme.foreground),
    'list.dropBackground': h(theme.background2),
    'list.focusBackground': h(theme.background),
    'list.focusForeground': h(theme.foreground),
    'list.focusHighlightForeground': h(theme.foreground),
    'list.focusOutline': h(theme.outline),
    'list.focusAndSelectionOutline': h(theme.outline),
    'list.highlightForeground': h(theme.foreground),
    'list.hoverBackground': h(theme.background2),
    'list.hoverForeground': h(theme.foreground),
    'list.inactiveSelectionBackground': h(theme.background),
    'list.inactiveSelectionForeground': h(theme.foreground),
    'list.inactiveSelectionIconForeground': h(theme.foreground),
    'list.inactiveFocusBackground': h(theme.background),
    'list.inactiveFocusOutline': h(theme.outline),
    'list.invalidItemForeground': h(theme.foreground),
    'list.errorForeground': h(theme.error),
    'list.warningForeground': h(theme.warning),
    'listFilterWidget.background': h(theme.background),
    'listFilterWidget.outline': h(theme.outline),
    'listFilterWidget.noMatchesOutline': h(theme.outline),
    'listFilterWidget.shadow': h(theme.shadow),
    'list.filterMatchBackground': h(theme.background2),
    'list.filterMatchBorder': h(theme.border),
    'list.deemphasizedForeground': h(theme.foreground),
    'tree.indentGuidesStroke': h(theme.stroke),
    'tree.inactiveIndentGuidesStroke': h(theme.stroke),
    'tree.tableColumnsBorder': h(theme.border),
    'tree.tableOddRowsBackground': h(theme.background),

    // Activity Bar
    'activityBar.background': h(theme.background),
    'activityBar.dropBorder': h(theme.border),
    'activityBar.foreground': h(theme.foreground),
    'activityBar.inactiveForeground': h(theme.foreground),
    'activityBar.border': h(theme.border),
    'activityBarBadge.background': h(theme.background),
    'activityBarBadge.foreground': h(theme.foreground),
    'activityBar.activeBorder': h(theme.border),
    'activityBar.activeBackground': h(theme.background),
    'activityBar.activeFocusBorder': h(theme.border),

    // Profiles
    'profileBadge.background': h(theme.background),
    'profileBadge.foreground': h(theme.foreground),

    // Side Bar
    'sideBar.background': h(theme.background),
    'sideBar.foreground': h(theme.foreground),
    'sideBar.border': h(theme.border),
    'sideBar.dropBackground': h(theme.background2),
    'sideBarTitle.foreground': h(theme.foreground),
    'sideBarSectionHeader.background': h(theme.background),
    'sideBarSectionHeader.foreground': h(theme.foreground),
    'sideBarSectionHeader.border': h(theme.border),

    // Minimap
    // 'minimap.findMatchHighlight':h(theme.''),
    // 'minimap.selectionHighlight':h(theme.''),
    // 'minimap.errorHighlight':h(theme.''),
    // 'minimap.warningHighlight':h(theme.''),
    // 'minimap.background':h(theme.''),
    // 'minimap.selectionOccurrenceHighlight':h(theme.''),
    // 'minimap.foregroundOpacity':h(theme.''),
    // 'minimap.infoHighlight':h(theme.''),
    // 'minimapSlider.background':h(theme.''),
    // 'minimapSlider.hoverBackground':h(theme.''),
    // 'minimapSlider.activeBackground':h(theme.''),
    // 'minimapGutter.addedBackground':h(theme.''),
    // 'minimapGutter.modifiedBackground':h(theme.''),
    // 'minimapGutter.deletedBackground':h(theme.''),

    // Editor Groups & Tabs
    'editorGroup.border': h(theme.border),
    'editorGroup.dropBackground': h(theme.background2),
    'editorGroupHeader.noTabsBackground': h(theme.background),
    'editorGroupHeader.tabsBackground': h(theme.background),
    'editorGroupHeader.tabsBorder': h(theme.border),
    'editorGroupHeader.border': h(theme.border),
    'editorGroup.emptyBackground': h(theme.background),
    'editorGroup.focusedEmptyBorder': h(theme.border),
    'editorGroup.dropIntoPromptForeground': h(theme.foreground),
    'editorGroup.dropIntoPromptBackground': h(theme.background),
    'editorGroup.dropIntoPromptBorder': h(theme.border),
    'tab.activeBackground': h(theme.background),
    'tab.unfocusedActiveBackground': h(theme.background),
    'tab.activeForeground': h(theme.foreground),
    'tab.border': h(theme.border),
    'tab.activeBorder': h(theme.border),
    'tab.unfocusedActiveBorder': h(theme.border),
    'tab.activeBorderTop': h(theme.border),
    'tab.unfocusedActiveBorderTop': h(theme.border),
    'tab.lastPinnedBorder': h(theme.border),
    'tab.inactiveBackground': h(theme.background),
    'tab.unfocusedInactiveBackground': h(theme.background),
    'tab.inactiveForeground': h(theme.foreground),
    'tab.unfocusedActiveForeground': h(theme.foreground),
    'tab.unfocusedInactiveForeground': h(theme.foreground),
    'tab.hoverBackground': h(theme.background),
    'tab.unfocusedHoverBackground': h(theme.background),
    'tab.hoverForeground': h(theme.foreground),
    'tab.unfocusedHoverForeground': h(theme.foreground),
    'tab.hoverBorder': h(theme.border),
    'tab.unfocusedHoverBorder': h(theme.border),
    'tab.activeModifiedBorder': h(theme.border),
    'tab.inactiveModifiedBorder': h(theme.border),
    'tab.unfocusedActiveModifiedBorder': h(theme.border),
    'tab.unfocusedInactiveModifiedBorder': h(theme.border),
    'editorPane.background': h(theme.background),
    'sideBySideEditor.horizontalBorder': h(theme.border),
    'sideBySideEditor.verticalBorder': h(theme.border),

    // Editor colors
    'editor.background': h(theme.background),
    'editor.foreground': h(theme.foreground),
    'editorLineNumber.foreground': h(theme.foreground),
    'editorLineNumber.activeForeground': h(theme.foreground2),
    'editorLineNumber.dimmedForeground': h(theme.foreground),
    'editorCursor.background': h(theme.background),
    'editorCursor.foreground': h(theme.foreground),
    // 'editorMultiCursor.primary.foreground': h(theme.foreground),
    // 'editorMultiCursor.primary.background': h(theme.background),
    // 'editorMultiCursor.secondary.foreground': h(theme.foreground),
    // 'editorMultiCursor.secondary.background': h(theme.background),
    // 'editor.placeholder.foreground': h(theme.foreground),
    'editor.selectionBackground': h(theme.background2),
    'editor.selectionForeground': h(theme.foreground),
    'editor.inactiveSelectionBackground': h(theme.background2),
    // 'editor.selectionHighlightBackground':h(theme.background2),
    // 'editor.selectionHighlightBorder':h(theme.border),
    // 'editor.wordHighlightBackground':h(theme.background),
    'editor.wordHighlightBorder': h(theme.border),
    // 'editor.wordHighlightStrongBackground':h(theme.background),
    'editor.wordHighlightStrongBorder': h(theme.border),
    // 'editor.wordHighlightTextBackground':h(theme.background),
    'editor.wordHighlightTextBorder': h(theme.border),
    // 'editor.findMatchBackground':h(theme.background2),
    // 'editor.findMatchHighlightBackground':h(theme.background),
    'editor.findMatchHighlightForeground': h(theme.foreground),
    // 'editor.findMatchHighlightBackground': h(theme.background),
    'editor.findRangeHighlightBackground': h(theme.background),
    'editor.findMatchBorder': h(theme.border),
    // 'editor.findMatchHighlightBorder':h(theme.colors.white),
    'editor.findRangeHighlightBorder': h(theme.border),
    'search.resultsInfoForeground': h(theme.foreground),
    // 'searchEditor.findMatchBackground':h(theme.oreground),
    // 'searchEditor.findMatchBorder':h(theme.oreground),
    // 'searchEditor.textInputBorder':h(theme.oreground),
    // 'editor.hoverHighlightBackground':h(theme.background),
    // 'editor.lineHighlightBackground':h(theme.background),
    'editor.lineHighlightBorder': h(theme.border),
    // 'editorWatermark.foreground': h(theme.foreground),
    // 'editorUnicodeHighlight.border':h(theme.background),
    // 'editorUnicodeHighlight.background':h(theme.background),
    'editorLink.activeForeground': h(theme.foreground2),
    // 'editor.rangeHighlightBackground': h(theme.background),
    // 'editor.rangeHighlightBorder': h(theme.border),
    'editor.symbolHighlightBackground': h(theme.background2),
    'editor.symbolHighlightBorder': h(theme.border),
    'editorWhitespace.foreground': h([theme.foreground3[0], theme.foreground[1]]),
    'editorIndentGuide.background': h(theme.background),
    // 'editorIndentGuide.background1': h(theme.background),
    // 'editorIndentGuide.background2':h(theme.background),
    // 'editorIndentGuide.background3':h(theme.colors.green),
    // 'editorIndentGuide.background4':h(theme.colors.red),
    // 'editorIndentGuide.background5':h(theme.colors.orange),
    // 'editorIndentGuide.background6':h(theme.colors.blue),
    'editorIndentGuide.activeBackground': h(theme.background3),
    // 'editorIndentGuide.activeBackground1': h(theme.background4),
    // 'editorIndentGuide.activeBackground2':h(theme.background),
    // 'editorIndentGuide.activeBackground3':h(theme.colors.green),
    // 'editorIndentGuide.activeBackground4':h(theme.colors.red),
    // 'editorIndentGuide.activeBackground5':h(theme.colors.orange),
    // 'editorIndentGuide.activeBackground6':h(theme.colors.blue),
    // 'editorInlayHint.background':h(theme.background),
    // 'editorInlayHint.foreground': h(theme.foreground3),
    // 'editorInlayHint.typeForeground': h(theme.foreground3),
    // 'editorInlayHint.typeBackground': h(theme.background),
    // 'editorInlayHint.parameterForeground': h(theme.foreground3),
    // 'editorInlayHint.parameterBackground': h(theme.background),
    'editorRuler.foreground': h(theme.foreground),
    'editor.linkedEditingBackground': h(theme.background2),
    'editorCodeLens.foreground': h([theme.foreground[0], theme.foreground3[1]]),
    'editorLightBulb.foreground': h(theme.foreground),
    'editorLightBulbAutoFix.foreground': h(theme.foreground),
    'editorBracketMatch.background': h(theme.background),
    'editorBracketMatch.border': h(theme.border),
    'editorBracketHighlight.foreground1': h(theme.bracket),
    'editorBracketHighlight.foreground2': h(theme.bracket2),
    'editorBracketHighlight.foreground3': h(theme.bracket3),
    'editorBracketHighlight.foreground4': h(theme.bracket4),
    'editorBracketHighlight.foreground5': h(theme.bracket5),
    'editorBracketHighlight.foreground6': h(theme.bracket6),
    'editorBracketHighlight.unexpectedBracket.foreground': h(theme.bracket7),
    // 'editorBracketPairGuide.activeBackground1': h(theme.background),
    // 'editorBracketPairGuide.activeBackground2': h(theme.background2),
    // 'editorBracketPairGuide.activeBackground3': h(theme.background3),
    // 'editorBracketPairGuide.activeBackground4': h(theme.background4),
    // 'editorBracketPairGuide.activeBackground5': h(theme.background),
    // 'editorBracketPairGuide.activeBackground6': h(theme.background),
    // 'editorBracketPairGuide.background1': h(theme.background),
    // 'editorBracketPairGuide.background2': h(theme.background2),
    // 'editorBracketPairGuide.background3': h(theme.background3),
    // 'editorBracketPairGuide.background4': h(theme.background4),
    // 'editorBracketPairGuide.background5': h(theme.background),
    // 'editorBracketPairGuide.background6': h(theme.background),
    // 'editor.foldBackground': h(theme.background2),
    'editor.foldPlaceholderForeground': h(theme.foreground3),
    'editorOverviewRuler.background': h(theme.background),
    'editorOverviewRuler.border': h(theme.border),
    'editorOverviewRuler.findMatchForeground': h(theme.foreground),
    // 'editorOverviewRuler.rangeHighlightForeground':h(theme.background),
    // 'editorOverviewRuler.selectionHighlightForeground':h(theme.background),
    // 'editorOverviewRuler.wordHighlightForeground':h(theme.background),
    // 'editorOverviewRuler.wordHighlightStrongForeground':h(theme.background),
    // 'editorOverviewRuler.wordHighlightTextForeground':h(theme.background),
    // 'editorOverviewRuler.modifiedForeground':h(theme.background),
    // 'editorOverviewRuler.addedForeground':h(theme.background),
    // 'editorOverviewRuler.deletedForeground':h(theme.background),
    // 'editorOverviewRuler.errorForeground':h(theme.background),
    // 'editorOverviewRuler.warningForeground':h(theme.background),
    // 'editorOverviewRuler.infoForeground':h(theme.background),
    // 'editorOverviewRuler.bracketMatchForeground':h(theme.background),
    // 'editorError.foreground': h(theme.error),
    // 'editorError.border': h(theme.error),
    // 'editorError.background':h(theme.olors.white),
    // 'editorWarning.foreground':h(theme.background),
    // 'editorWarning.border':h(theme.background),
    // 'editorWarning.background':h(theme.background),
    // 'editorInfo.foreground':h(theme.background),
    // 'editorInfo.border':h(theme.background),
    // 'editorInfo.background':h(theme.background),
    // 'editorHint.foreground':h(theme.background),
    // 'editorHint.border':h(theme.order),
    // 'problemsErrorIcon.foreground':h(theme.background),
    // 'problemsWarningIcon.foreground':h(theme.background),
    // 'problemsInfoIcon.foreground':h(theme.background),
    // 'editorUnnecessaryCode.border':h(theme.background),
    // 'editorUnnecessaryCode.opacity':h(theme.background),
    'editorGutter.background': h(theme.background),
    'editorGutter.modifiedBackground': h(theme.background3),
    // 'editorGutter.addedBackground':h(theme.background),
    // 'editorGutter.deletedBackground':h(theme.background),
    // 'editorGutter.commentRangeForeground':h(theme.background),
    // 'editorGutter.commentGlyphForeground':h(theme.background),
    // 'editorGutter.commentUnresolvedGlyphForeground':h(theme.background),
    // 'editorGutter.foldingControlForeground':h(theme.background),
    // 'editorCommentsWidget.resolvedBorder':h(theme.background),
    // 'editorCommentsWidget.unresolvedBorder':h(theme.background),
    // 'editorCommentsWidget.rangeBackground':h(theme.background),
    // 'editorCommentsWidget.rangeActiveBackground':h(theme.background),

    // Diff editor colors
    // 'diffEditor.insertedTextBackground': h(theme.insert),
    'diffEditor.insertedTextBorder': h(theme.border3),
    // 'diffEditor.removedTextBackground': h(theme.remove),
    'diffEditor.removedTextBorder': h(theme.border4),
    'diffEditor.border': h(theme.border),
    // 'diffEditor.diagonalFill':h(theme.background),
    // 'diffEditor.insertedLineBackground': h(theme.background),
    // 'diffEditor.removedLineBackground': h(theme.background),
    'diffEditorGutter.insertedLineBackground': h(theme.background5),
    'diffEditorGutter.removedLineBackground': h(theme.background6),
    // 'diffEditorOverview.insertedForeground': h(theme.background5),
    // 'diffEditorOverview.removedForeground': h(theme.background6),
    'diffEditor.unchangedRegionBackground': h(theme.background2),
    'diffEditor.unchangedRegionForeground': h(theme.foreground),
    // 'diffEditor.unchangedCodeBackground': h(theme.background),
    // 'diffEditor.move.border': h(theme.border4),
    // 'diffEditor.moveActive.border':h(theme.background),
    // 'multiDiffEditor.headerBackground':h(theme.background2),
    // 'multiDiffEditor.background':h(theme.background2),
    // 'multiDiffEditor.border':h(theme.background2),

    // Chat colors
    // 'chat.requestBorder':h(theme.background),
    // 'chat.slashCommandBackground':h(theme.background),
    // 'chat.slashCommandForeground':h(theme.background),

    // Inline Chat colors
    // 'inlineChat.background':h(theme.background),
    // 'inlineChat.border':h(theme.background),
    // 'inlineChat.shadow':h(theme.background),
    // 'inlineChat.regionHighlight':h(theme.background),
    // 'inlineChatInput.border':h(theme.background),
    // 'inlineChatInput.focusBorder':h(theme.background),
    // 'inlineChatInput.placeholderForeground':h(theme.background),
    // 'inlineChatInput.background':h(theme.background),
    // 'inlineChatDiff.inserted':h(theme.background),
    // 'inlineChatDiff.removed':h(theme.background),

    // Editor widget colors
    // 'editorWidget.foreground':h(theme.foreground),
    // 'editorWidget.background':h(theme.background),
    // 'editorWidget.border':h(theme.border),
    // 'editorWidget.resizeBorder':h(theme.border),
    // 'editorSuggestWidget.background':h(theme.background),
    // 'editorSuggestWidget.border':h(theme.background),
    // 'editorSuggestWidget.foreground':h(theme.background),
    // 'editorSuggestWidget.focusHighlightForeground':h(theme.background),
    // 'editorSuggestWidget.highlightForeground':h(theme.background),
    // 'editorSuggestWidget.selectedBackground':h(theme.background),
    // 'editorSuggestWidget.selectedForeground':h(theme.background),
    // 'editorSuggestWidget.selectedIconForeground':h(theme.background),
    // 'editorSuggestWidgetStatus.foreground':h(theme.background),
    // 'editorHoverWidget.foreground':h(theme.foreground),
    // 'editorHoverWidget.background':h(theme.background),
    // 'editorHoverWidget.border':h(theme.border),
    // 'editorHoverWidget.highlightForeground':h(theme.background),
    // 'editorHoverWidget.statusBarBackground':h(theme.background),
    // 'editorGhostText.border':h(theme.background),
    // 'editorGhostText.background':h(theme.background),
    // 'editorGhostText.foreground':h(theme.background),
    // 'editorStickyScroll.background':h(theme.background),
    // 'editorStickyScrollHover.background':h(theme.background),
    // 'debugExceptionWidget.background':h(theme.background),
    // 'debugExceptionWidget.border':h(theme.background),
    // 'editorMarkerNavigation.background':h(theme.background),
    // 'editorMarkerNavigationError.background':h(theme.background),
    // 'editorMarkerNavigationWarning.background':h(theme.background),
    // 'editorMarkerNavigationInfo.background':h(theme.background),
    // 'editorMarkerNavigationError.headerBackground':h(theme.background),
    // 'editorMarkerNavigationWarning.headerBackground':h(theme.background),
    // 'editorMarkerNavigationInfo.headerBackground':h(theme.background),

    // Peek view colors
    // 'peekView.border':h(theme.background),
    // 'peekViewEditor.background':h(theme.background),
    // 'peekViewEditorGutter.background':h(theme.background),
    // 'peekViewEditor.matchHighlightBackground':h(theme.background),
    // 'peekViewEditor.matchHighlightBorder':h(theme.background),
    // 'peekViewResult.background':h(theme.background),
    // 'peekViewResult.fileForeground':h(theme.background),
    // 'peekViewResult.lineForeground':h(theme.background),
    // 'peekViewResult.matchHighlightBackground':h(theme.background),
    // 'peekViewResult.selectionBackground':h(theme.background),
    // 'peekViewResult.selectionForeground':h(theme.background),
    // 'peekViewTitle.background':h(theme.background),
    // 'peekViewTitleDescription.foreground':h(theme.background),
    // 'peekViewTitleLabel.foreground':h(theme.background),
    // 'peekViewEditorStickyScroll.background':h(theme.background),

    // Merge conflicts colors
    // 'merge.currentHeaderBackground':h(theme.background),
    // 'merge.currentContentBackground':h(theme.background),
    // 'merge.incomingHeaderBackground':h(theme.background),
    // 'merge.incomingContentBackground':h(theme.background),
    // 'merge.border':h(theme.background),
    // 'merge.commonContentBackground':h(theme.background),
    // 'merge.commonHeaderBackground':h(theme.background),
    // 'editorOverviewRuler.currentContentForeground':h(theme.background),
    // 'editorOverviewRuler.incomingContentForeground':h(theme.background),
    // 'editorOverviewRuler.commonContentForeground':h(theme.background),
    // 'editorOverviewRuler.commentForeground':h(theme.background),
    // 'editorOverviewRuler.commentUnresolvedForeground':h(theme.background),
    // 'mergeEditor.change.background':h(theme.background),
    // 'mergeEditor.change.word.background':h(theme.background),
    // 'mergeEditor.conflict.unhandledUnfocused.border':h(theme.background),
    // 'mergeEditor.conflict.unhandledFocused.border':h(theme.background),
    // 'mergeEditor.conflict.handledUnfocused.border':h(theme.background),
    // 'mergeEditor.conflict.handledFocused.border':h(theme.background),
    // 'mergeEditor.conflict.handled.minimapOverViewRuler':h(theme.background),
    // 'mergeEditor.conflict.unhandled.minimapOverViewRuler':h(theme.background),
    // 'mergeEditor.conflictingLines.background':h(theme.background),
    // 'mergeEditor.changeBase.background':h(theme.background),
    // 'mergeEditor.changeBase.word.background':h(theme.background),
    // 'mergeEditor.conflict.input1.background':h(theme.background),
    // 'mergeEditor.conflict.input2.background':h(theme.background),

    // Panel colors
    'panel.background': h(theme.background),
    'panel.border': h(theme.border),
    'panel.dropBorder': h(theme.border2),
    'panelTitle.activeBorder': h(theme.border),
    'panelTitle.activeForeground': h(theme.foreground),
    'panelTitle.inactiveForeground': h(theme.foreground),
    'panelInput.border': h(theme.border),
    // 'panelSection.border':h(theme.error),
    // 'panelSection.dropBackground':h(theme.background),
    // 'panelSectionHeader.background':h(theme.background),
    // 'panelSectionHeader.foreground':h(theme.background),
    // 'panelSectionHeader.border':h(theme.background),

    // Status Bar colors
    'statusBar.background': h(theme.background),
    'statusBar.foreground': h(theme.foreground),
    'statusBar.border': h(theme.border),
    'statusBar.debuggingBackground': h(theme.background),
    'statusBar.debuggingForeground': h(theme.foreground),
    'statusBar.debuggingBorder': h(theme.border),
    'statusBar.noFolderForeground': h(theme.foreground),
    'statusBar.noFolderBackground': h(theme.background),
    'statusBar.noFolderBorder': h(theme.border),
    // 'statusBarItem.activeBackground':h(theme.background),
    // 'statusBarItem.hoverForeground':h(theme.foreground),
    // 'statusBarItem.hoverBackground':h(theme.background),
    // 'statusBarItem.prominentForeground':h(theme.error),
    // 'statusBarItem.prominentBackground':h(theme.background),
    // 'statusBarItem.prominentHoverForeground':h(theme.background),
    // 'statusBarItem.prominentHoverBackground':h(theme.background),
    // 'statusBarItem.remoteBackground':h(theme.background),
    // 'statusBarItem.remoteForeground':h(theme.background),
    // 'statusBarItem.remoteHoverBackground':h(theme.background),
    // 'statusBarItem.remoteHoverForeground':h(theme.background),
    // 'statusBarItem.errorBackground':h(theme.background),
    // 'statusBarItem.errorForeground':h(theme.error),
    // 'statusBarItem.errorHoverBackground':h(theme.background),
    // 'statusBarItem.errorHoverForeground':h(theme.background),
    // 'statusBarItem.warningBackground':h(theme.background),
    // 'statusBarItem.warningForeground':h(theme.background),
    // 'statusBarItem.warningHoverBackground':h(theme.background),
    // 'statusBarItem.warningHoverForeground':h(theme.background),
    // 'statusBarItem.compactHoverBackground':h(theme.background),
    // 'statusBarItem.focusBorder':h(theme.background),
    // 'statusBar.focusBorder':h(theme.background),
    // 'statusBarItem.offlineBackground':h(theme.background),
    // 'statusBarItem.offlineForeground':h(theme.background),
    // 'statusBarItem.offlineHoverForeground':h(theme.background),
    // 'statusBarItem.offlineHoverBackground':h(theme.background),

    // Title Bar colors
    // 'titleBar.activeBackground':h(theme.background),
    // 'titleBar.activeForeground':h(theme.background),
    // 'titleBar.inactiveBackground':h(theme.background),
    // 'titleBar.inactiveForeground':h(theme.background),
    // 'titleBar.border':h(theme.background),

    // Menu Bar colors
    // 'menubar.selectionForeground':h(theme.background),
    // 'menubar.selectionBackground':h(theme.background),
    // 'menubar.selectionBorder':h(theme.background),
    // 'menu.foreground':h(theme.background),
    // 'menu.background':h(theme.background),
    // 'menu.selectionForeground':h(theme.background),
    // 'menu.selectionBackground':h(theme.background),
    // 'menu.selectionBorder':h(theme.background),
    // 'menu.separatorBackground':h(theme.background),
    // 'menu.border':h(theme.background),

    // Command Center colors
    // 'commandCenter.foreground':h(theme.background),
    // 'commandCenter.activeForeground':h(theme.background),
    // 'commandCenter.background':h(theme.background),
    // 'commandCenter.activeBackground':h(theme.background),
    // 'commandCenter.border':h(theme.background),
    // 'commandCenter.inactiveForeground':h(theme.background),
    // 'commandCenter.inactiveBorder':h(theme.background),
    // 'commandCenter.activeBorder':h(theme.background),
    // 'commandCenter.debuggingBackground':h(theme.background),

    // Notification colors
    'notificationCenter.border': h(theme.border),
    'notificationCenterHeader.foreground': h(theme.foreground),
    'notificationCenterHeader.background': h(theme.background),
    'notificationToast.border': h(theme.border),
    'notifications.foreground': h(theme.foreground),
    'notifications.background': h(theme.background),
    'notifications.border': h(theme.border),
    // 'notificationLink.foreground':h(theme.background),
    // 'notificationsErrorIcon.foreground':h(theme.background),
    // 'notificationsWarningIcon.foreground':h(theme.background),
    // 'notificationsInfoIcon.foreground':h(theme.background),

    // Banner colors
    // 'banner.background':h(theme.background),
    // 'banner.foreground':h(theme.background),
    // 'banner.iconForeground':h(theme.background),

    // Extensions colors
    'extensionButton.prominentForeground': h(theme.foreground),
    // 'extensionButton.prominentBackground': h(theme.background),
    'extensionButton.prominentHoverBackground': h(theme.background),
    // 'extensionButton.background':h(theme.background),
    'extensionButton.foreground': h(theme.foreground),
    'extensionButton.hoverBackground': h(theme.background),
    'extensionButton.separator': h(theme.separator),
    // 'extensionBadge.remoteBackground':h(theme.background),
    // 'extensionBadge.remoteForeground':h(theme.background),
    // 'extensionIcon.starForeground':h(theme.background),
    // 'extensionIcon.verifiedForeground':h(theme.background),
    // 'extensionIcon.preReleaseForeground':h(theme.background),
    // 'extensionIcon.sponsorForeground':h(theme.background),

    // Quick picker colors
    // 'pickerGroup.border':h(theme.background),
    // 'pickerGroup.foreground':h(theme.background),
    // 'quickInput.background':h(theme.background),
    // 'quickInput.foreground':h(theme.background),
    // 'quickInputList.focusBackground':h(theme.background),
    // 'quickInputList.focusForeground':h(theme.background),
    // 'quickInputList.focusIconForeground':h(theme.background),
    // 'quickInputTitle.background':h(theme.background),

    // Keybinding label colors
    'keybindingLabel.background': h(theme.background),
    'keybindingLabel.foreground': h(theme.foreground),
    'keybindingLabel.border': h(theme.border),
    'keybindingLabel.bottomBorder': h(theme.border),

    // Keyboard shortcut table colors
    'keybindingTable.headerBackground': h(theme.background),
    'keybindingTable.rowsBackground': h(theme.background),

    // Integrated Terminal colors
    'terminal.background': h(theme.background),
    'terminal.border': h(theme.border),
    'terminal.foreground': h(theme.foreground),
    // 'terminal.ansiBlack':h(theme.background),
    // 'terminal.ansiBlue':h(theme.background),
    // 'terminal.ansiBrightBlack':h(theme.background),
    // 'terminal.ansiBrightBlue':h(theme.background),
    // 'terminal.ansiBrightCyan':h(theme.background),
    // 'terminal.ansiBrightGreen':h(theme.background),
    // 'terminal.ansiBrightMagenta':h(theme.background),
    // 'terminal.ansiBrightRed':h(theme.background),
    // 'terminal.ansiBrightWhite':h(theme.background),
    // 'terminal.ansiBrightYellow':h(theme.background),
    // 'terminal.ansiCyan':h(theme.background),
    // 'terminal.ansiGreen':h(theme.background),
    // 'terminal.ansiMagenta':h(theme.background),
    // 'terminal.ansiRed':h(theme.background),
    // 'terminal.ansiWhite':h(theme.background),
    // 'terminal.ansiYellow':h(theme.background),
    // 'terminal.selectionBackground':h(theme.background),
    // 'terminal.selectionForeground':h(theme.background),
    // 'terminal.inactiveSelectionBackground':h(theme.background),
    'terminal.findMatchBackground': h(theme.background),
    'terminal.findMatchBorder': h(theme.border),
    // 'terminal.findMatchHighlightBackground':h(theme.background),
    'terminal.findMatchHighlightBorder': h(theme.border),
    // 'terminal.hoverHighlightBackground':h(theme.background),
    'terminalCursor.background': h(theme.background),
    'terminalCursor.foreground': h(theme.foreground),
    // 'terminal.dropBackground':h(theme.background),
    // 'terminal.tab.activeBorder':h(theme.background),
    // 'terminalCommandDecoration.defaultBackground':h(theme.background),
    // 'terminalCommandDecoration.successBackground':h(theme.background),
    // 'terminalCommandDecoration.errorBackground':h(theme.background),
    // 'terminalOverviewRuler.cursorForeground':h(theme.background),
    // 'terminalOverviewRuler.findMatchForeground':h(theme.background),

    // Debug colors
    'debugToolBar.background': h(theme.background),
    'debugToolBar.border': h(theme.border),
    'editor.stackFrameHighlightBackground': h(theme.background2),
    'editor.focusedStackFrameHighlightBackground': h(theme.background2),
    'editor.inlineValuesForeground': h(theme.foreground),
    'editor.inlineValuesBackground': h(theme.background2),
    // 'debugView.exceptionLabelForeground':h(theme.background),
    // 'debugView.exceptionLabelBackground':h(theme.background),
    'debugView.stateLabelForeground': h(theme.foreground),
    'debugView.stateLabelBackground': h(theme.background2),
    'debugView.valueChangedHighlight': h(theme.highlight),
    'debugTokenExpression.name': h(theme.highlight2),
    // 'debugTokenExpression.value':h(theme.background),
    // 'debugTokenExpression.string':h(theme.background),
    // 'debugTokenExpression.boolean':h(theme.background),
    // 'debugTokenExpression.number':h(theme.background),
    // 'debugTokenExpression.error':h(theme.background),

    // Testing colors
    // 'testing.iconFailed':h(theme.background),
    // 'testing.iconErrored':h(theme.background),
    // 'testing.iconPassed':h(theme.background),
    // 'testing.runAction':h(theme.background),
    // 'testing.iconQueued':h(theme.background),
    // 'testing.iconUnset':h(theme.background),
    // 'testing.iconSkipped':h(theme.background),
    // 'testing.peekBorder':h(theme.background),
    // 'testing.peekHeaderBackground':h(theme.background),
    // 'testing.message.error.decorationForeground':h(theme.background),
    // 'testing.message.error.lineBackground':h(theme.background),
    // 'testing.message.info.decorationForeground':h(theme.background),
    // 'testing.message.info.lineBackground':h(theme.background),

    // Welcome page colors
    // 'welcomePage.background':h(theme.background),
    // 'welcomePage.progress.background':h(theme.background),
    // 'welcomePage.progress.foreground':h(theme.background),
    // 'welcomePage.tileBackground':h(theme.background),
    // 'welcomePage.tileHoverBackground':h(theme.background),
    // 'welcomePage.tileBorder':h(theme.background),
    // 'walkThrough.embeddedEditorBackground':h(theme.background),
    // 'walkthrough.stepTitle.foreground':h(theme.background),

    // Git colors
    // 'gitDecoration.addedResourceForeground':h(theme.background),
    // 'gitDecoration.modifiedResourceForeground':h(theme.background),
    // 'gitDecoration.deletedResourceForeground':h(theme.background),
    // 'gitDecoration.renamedResourceForeground':h(theme.background),
    // 'gitDecoration.stageModifiedResourceForeground':h(theme.background),
    // 'gitDecoration.stageDeletedResourceForeground':h(theme.background),
    // 'gitDecoration.untrackedResourceForeground':h(theme.background),
    // 'gitDecoration.ignoredResourceForeground':h(theme.background),
    // 'gitDecoration.conflictingResourceForeground':h(theme.background),
    // 'gitDecoration.submoduleResourceForeground':h(theme.background),

    // Settings Editor colors
    // 'settings.headerForeground':h(theme.background),
    // 'settings.modifiedItemIndicator':h(theme.background),
    // 'settings.dropdownBackground':h(theme.background),
    // 'settings.dropdownForeground':h(theme.background),
    // 'settings.dropdownBorder':h(theme.background),
    // 'settings.dropdownListBorder':h(theme.background),
    // 'settings.checkboxBackground':h(theme.background),
    // 'settings.checkboxForeground':h(theme.background),
    // 'settings.checkboxBorder':h(theme.background),
    // 'settings.rowHoverBackground':h(theme.background),
    // 'settings.textInputBackground':h(theme.background),
    // 'settings.textInputForeground':h(theme.background),
    // 'settings.textInputBorder':h(theme.background),
    // 'settings.numberInputBackground':h(theme.background),
    // 'settings.numberInputForeground':h(theme.background),
    // 'settings.numberInputBorder':h(theme.background),
    // 'settings.focusedRowBackground':h(theme.background),
    // 'settings.focusedRowBorder':h(theme.background),
    // 'settings.headerBorder':h(theme.background),
    // 'settings.sashBorder':h(theme.background),
    // 'settings.settingsHeaderHoverForeground':h(theme.background),

    // Breadcrumbs colors
    'breadcrumb.foreground': h(theme.foreground),
    // 'breadcrumb.background':h(theme.background),
    'breadcrumb.focusForeground': h(theme.foreground),
    'breadcrumb.activeSelectionForeground': h(theme.foreground),
    // 'breadcrumbPicker.background':h(theme.background),

    // Snippets colors
    'editor.snippetTabstopHighlightBackground': h(theme.background2),
    'editor.snippetTabstopHighlightBorder': h(theme.border),
    // 'editor.snippetFinalTabstopHighlightBackground':h(theme.background),
    // 'editor.snippetFinalTabstopHighlightBorder':h(theme.border),

    // Symbol Icons colors
    // 'symbolIcon.arrayForeground':h(theme.background),
    // 'symbolIcon.booleanForeground':h(theme.background),
    // 'symbolIcon.classForeground':h(theme.background),
    // 'symbolIcon.colorForeground':h(theme.background),
    // 'symbolIcon.constantForeground':h(theme.background),
    // 'symbolIcon.constructorForeground':h(theme.background),
    // 'symbolIcon.enumeratorForeground':h(theme.background),
    // 'symbolIcon.enumeratorMemberForeground':h(theme.background),
    // 'symbolIcon.eventForeground':h(theme.background),
    // 'symbolIcon.fieldForeground':h(theme.background),
    // 'symbolIcon.fileForeground':h(theme.background),
    // 'symbolIcon.folderForeground':h(theme.background),
    // 'symbolIcon.functionForeground':h(theme.background),
    // 'symbolIcon.interfaceForeground':h(theme.background),
    // 'symbolIcon.keyForeground':h(theme.background),
    // 'symbolIcon.keywordForeground':h(theme.background),
    // 'symbolIcon.methodForeground':h(theme.background),
    // 'symbolIcon.moduleForeground':h(theme.background),
    // 'symbolIcon.namespaceForeground':h(theme.background),
    // 'symbolIcon.nullForeground':h(theme.background),
    // 'symbolIcon.numberForeground':h(theme.background),
    // 'symbolIcon.objectForeground':h(theme.background),
    // 'symbolIcon.operatorForeground':h(theme.background),
    // 'symbolIcon.packageForeground':h(theme.background),
    // 'symbolIcon.propertyForeground':h(theme.background),
    // 'symbolIcon.referenceForeground':h(theme.background),
    // 'symbolIcon.snippetForeground':h(theme.background),
    // 'symbolIcon.stringForeground':h(theme.background),
    // 'symbolIcon.structForeground':h(theme.background),
    // 'symbolIcon.textForeground':h(theme.background),
    // 'symbolIcon.typeParameterForeground':h(theme.background),
    // 'symbolIcon.unitForeground':h(theme.background),
    // 'symbolIcon.variableForeground':h(theme.background),

    // Debug Icons colors
    // 'debugIcon.breakpointForeground':h(theme.background),
    // 'debugIcon.breakpointDisabledForeground':h(theme.background),
    // 'debugIcon.breakpointUnverifiedForeground':h(theme.background),
    // 'debugIcon.breakpointCurrentStackframeForeground':h(theme.background),
    // 'debugIcon.breakpointStackframeForeground':h(theme.background),
    // 'debugIcon.startForeground':h(theme.background),
    // 'debugIcon.pauseForeground':h(theme.background),
    // 'debugIcon.stopForeground':h(theme.background),
    // 'debugIcon.disconnectForeground':h(theme.background),
    // 'debugIcon.restartForeground':h(theme.background),
    // 'debugIcon.stepOverForeground':h(theme.background),
    // 'debugIcon.stepIntoForeground':h(theme.background),
    // 'debugIcon.stepOutForeground':h(theme.background),
    // 'debugIcon.continueForeground':h(theme.background),
    // 'debugIcon.stepBackForeground':h(theme.background),
    // 'debugConsole.infoForeground':h(theme.background),
    // 'debugConsole.warningForeground':h(theme.background),
    // 'debugConsole.errorForeground':h(theme.background),
    // 'debugConsole.sourceForeground':h(theme.background),
    // 'debugConsoleInputIcon.foreground':h(theme.background),

    // Notebook colors
    // 'notebook.editorBackground':h(theme.background),
    // 'notebook.cellBorderColor':h(theme.background),
    // 'notebook.cellHoverBackground':h(theme.background),
    // 'notebook.cellInsertionIndicator':h(theme.background),
    // 'notebook.cellStatusBarItemHoverBackground':h(theme.background),
    // 'notebook.cellToolbarSeparator':h(theme.background),
    // 'notebook.cellEditorBackground':h(theme.background),
    // 'notebook.focusedCellBackground':h(theme.background),
    // 'notebook.focusedCellBorder':h(theme.background),
    // 'notebook.focusedEditorBorder':h(theme.background),
    // 'notebook.inactiveFocusedCellBorder':h(theme.background),
    // 'notebook.inactiveSelectedCellBorder':h(theme.background),
    // 'notebook.outputContainerBackgroundColor':h(theme.background),
    // 'notebook.outputContainerBorderColor':h(theme.background),
    // 'notebook.selectedCellBackground':h(theme.background),
    // 'notebook.selectedCellBorder':h(theme.background),
    // 'notebook.symbolHighlightBackground':h(theme.background),
    // 'notebookScrollbarSlider.activeBackground':h(theme.background),
    // 'notebookScrollbarSlider.background':h(theme.background),
    // 'notebookScrollbarSlider.hoverBackground':h(theme.background),
    // 'notebookStatusErrorIcon.foreground':h(theme.background),
    // 'notebookStatusRunningIcon.foreground':h(theme.background),
    // 'notebookStatusSuccessIcon.foreground':h(theme.background),
    // 'notebookEditorOverviewRuler.runningCellForeground':h(theme.background),

    // Chart colors
    // 'charts.foreground':h(theme.background),
    // 'charts.lines':h(theme.background),
    // 'charts.red':h(theme.background),
    // 'charts.blue':h(theme.background),
    // 'charts.yellow':h(theme.background),
    // 'charts.orange':h(theme.background),
    // 'charts.green':h(theme.background),
    // 'charts.purple':h(theme.background),

    // Ports Colors
    // 'ports.iconRunningProcessForeground':h(theme.background),

    // Comments View colors
    // 'commentsView.resolvedIcon':h(theme.background),
    // 'commentsView.unresolvedIcon':h(theme.background),

    // Action Bar colors
    'actionBar.toggledBackground': h(theme.background2),

    // Simple Find Widget
    // 'simpleFindWidget.sashBorder':h(theme.background),
  }
}

export default function getTheme(isColor = false) {
  return {
    name: isColor ? 'E-Ink Color' : 'E-Ink',
    base: 'hc-light',
    $schema: 'vscode://schemas/color-theme',
    colors: getThemeColors(isColor),
    tokenColors: getTokenColors(isColor),
    ...getsemanticTokenColors(isColor),
  }
}
